name: Broken Link Checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # https://github.com/lycheeverse/lychee-action#security-tip
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.js' './**/*.ts'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
