name: Broken Link Checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@f796c8b7d468feb9b8c0a46da3fac0af6874d374 # https://github.com/lycheeverse/lychee-action#security-tip
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.js' './**/*.ts'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
