name: Broken Link Checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@9ace499fe66cee282a29eaa628fdac2c72fa087f # https://github.com/lycheeverse/lychee-action#security-tip
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.js' './**/*.ts'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
