name: Broken Link Checker

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@97189f2c0a3c8b0cb0e704fd4e878af6e5e2b2c5 # https://github.com/lycheeverse/lychee-action#security-tip
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.js' './**/*.ts'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
